### ISSUE TITLE
Enable scale item column

### ISSUE THREAD

**Issue by jacknlliu** [ros-visualization/rqt_topic#1]
In rqt plugin `topic monitor`, we can't scale the width of item column, this lead that we can't see every detail easily.

![rqt_topic](https://user-images.githubusercontent.com/6220143/32412333-124a4376-c22f-11e7-9c3a-e667d1f2594a.png)

reference to https://github.com/ros-visualization/rqt/issues/125

**Comment by dirk-thomas** [comment]
You should be able to right-click the table header to switch between two different modes:
* automatically size all columns to fit the content (default)
* allow manually resizing the columns

The toggling behavior seems to be broken in the currently released version when using Qt 5. Please see #2 for a fix for that.
