### ISSUE TITLE
Releasing rqt_topic for crystal

### ISSUE THREAD

**Issue by mlautman** [ros-visualization/rqt_topic#12]
@dirk-thomas This should be ready for release. If you invite me to collaborate on the release repo I can take care of getting that out.

**Comment by dirk-thomas** [comment]
I sent you an invite for the ROS 2 release repo: https://github.com/ros2-gbp/rqt_topic-release

Thanks for taking care of the release.

**Comment by dirk-thomas** [comment]
Done long time ago.
