### ISSUE TITLE
Inconsistent ordering of sensor_msgs/PointField

### ISSUE THREAD

**Issue by pauljurczak** [ros-visualization/rqt_topic#20]
Components of sensor_msgs/PointField are displayed in inconsistent order:

![Screenshot from 2020-01-11 17-50-13](https://user-images.githubusercontent.com/4933032/72212696-ef72a800-349d-11ea-8a88-0bb6171c7a6a.png)

**Comment by dirk-thomas** [comment]
After taking another closer look to your screenshot the `Value` column shows an order indicator. So the view is ordered by the values in that column which explains the order you are seeing.

If you click on the first column header the order should be alphabetic based on the topic / field name.

**Comment by pauljurczak** [comment]
> the view is ordered by the values in that column

I disagree. The first 3 items are indeed ordered by `Value`: ['x' 0 1 7], ['y' 1 4 7] and ['z' 1 7 8]. But what about the next 2 items: ['intensity' 1 16 7] and ['rind' 1 24 4], which are not ordered?

**Comment by dirk-thomas** [comment]
> But what about the next 2 items: ['intensity' 1 16 7] and ['rind' 1 24 4], which are not ordered?

They are actually ordered. The numbers won't be ordered by value but by their string representation.

**Comment by dirk-thomas** [comment]
Please see #22 and #23 which each provide improvements to the non-intuitive ordering.
