### ISSUE TITLE
show leaf topics in topic monitor

### ISSUE THREAD

**Issue by theotromp97** [ros-visualization/rqt_topic#32]
Hi,

I would like to show all topics, including the topics without subs or pubs (leaf topics).

Is there a possibility for this in the rqt topic monitor?

Thanks

**Comment by audrow** [comment]
Hi @theotromp97, I believe that leaf packages already display in the topic monitor. I just checked with ROS 2 rolling and I can see leaf publishers and leaf subscribers in the topic monitor (make sure to refresh the topic monitor, if new publishers or subscribers are added).

You mentioned 'roscore' in the comment issue description, before I edited the description. This repository only has ROS 2 branches in it, so perhaps this question is in the wrong place.

Also, in general, questions like this are good for [ROS Answers](https://answers.ros.org/questions/). If you find out something doesn't exist, feel free to make an issue with a feature request.
