### ISSUE TITLE
Update Frequency of topic values

### ISSUE THREAD

**Issue by jzhang046** [ros-visualization/rqt_topic#5]
The values of the monitored topics updates around every second in the monitor. Is there a way to get faster update? 
I have verified the realtime values using `rostopic echo`.

**Comment by dirk-thomas** [comment]
The information is currently polled once every second (every [1000ms](https://github.com/ros-visualization/rqt_topic/blob/eaf5b36306598cb80a82990fbeb5e2d014923cce/src/rqt_topic/topic_widget.py#L114)). Please feel free to try a smaller value, e.g. `200ms` and check if that works better for you. If it is not too low please make a PR for that change (it just shouldn't use too much resources by polling the info every `10ms` e.g.).

**Comment by dirk-thomas** [comment]
Closing due to long time of inactivity.
